dist: trusty
language: python
addons:
  sonarcloud:
    organization: "borisv13-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN2 # encrypted value of your token
python:
  - "3.6"

install:
  - pip install -r requirements.txt
before_script:
  - cd backend
script:
  - pytest backend
#  - py.test --cov-report term --cov=.
#  - coverage xml
services:
  - sqlite
env:
  - DJANGO=2.2.6 DJANGO_SETTINGS_MODULE=backend.kot.settings PYTHONPATH=../
after_success:
  - codecov

